version: 2.1
orbs:
  node: circleci/node@2.0.1
  win: circleci/windows@2.2.0
jobs:
  test-linux:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm ci
      - run: npm run junit
      - store_test_results:
          path: test/results

  test-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - run: npm ci
      - run: npm run junit
      - store_test_results:
          path: test/results
workflows:
    test:
      jobs:
        - test-linux
        - test-windows
