version: 2.1
orbs:
  node: circleci/node@1.1.6
  win: circleci/windows@2.2.0
jobs:
  test-linux:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run junit
      - store_test_results:
          path: test/results

  test-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run junit
      - store_test_results:
          path: test/results
workflows:
    test:
      jobs:
        - test-linux
        - test-windows
