version: 2.1
orbs:
  node: circleci/node@2.0.1
  win: circleci/windows@2.2.0
commands:
  test:
    steps:
      - checkout
      - run: npm ci
      - run: npm run junit
      - store_test_results:
          path: test/results
jobs:
  test-linux:
    executor:
      name: node/default
      tag: "10.14"
    steps:
      - run: npm install -g npm@latest
      - test

  test-windows:
    executor:
      name: win/default
    steps:
      - test
  
  release:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm ci
      - run: npm run semantic-release
      

workflows:
    test-and-release:
      jobs:
        - test-linux
        - test-windows
        - release:
            requires:
              - test-linux
              - test-windows
      